name: charm
version: 2.2
summary: charm and charm-tools
description: charmstore-client and charm-tools
confinement: classic
grade: stable

apps:
  charm:
    # These VARs need to go away to not leak into the environment (if they are unwanted).
    command: env PATH=$SNAP/bin:$SNAP/usr/bin:$SNAP/libexec/git-core:$PATH GIT_TEMPLATE_DIR=$SNAP/share/git-core/templates UNIXCONFDIR=$SNAP/etc PREFIX=$SNAP GIT_EXEC_PATH=$SNAP/usr/lib/git-core LC_ALL=C.UTF-8 $SNAP/bin/charm
#   plugs: [network, network-bind, home]
parts:
  charm:
    source: https://github.com/juju/charmstore-client.git
    source-tag: 2.2.0
    source-type: git
    plugin: godeps
    go-importpath: github.com/juju/charmstore-client
    build-packages:
      - bzr
  charm-terms:
    source: https://github.com/juju/terms-client.git
    source-tag: v1.0.1
    source-type: git
    plugin: godeps
    go-importpath: github.com/juju/terms-client
  python2:
    source: https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tar.xz
    plugin: autotools
    configflags:
      - --prefix=/usr
      - --with-ensurepip=install
    build-packages:
      - libssl-dev
      - libbz2-dev
    stage:
      - -usr/bin/2to3
    prime:
      - -usr/include
  charm-tools:
    source: https://github.com/juju/charm-tools.git
    source-tag: v2.2.0
    plugin: python
    python-version: python2
    build-packages:
      - build-essential
    python-packages:
      - simplejson
      - launchpadlib
      - bz2file
      - bzr
      - Mercurial
    stage-packages:
      - dpkg
      - libapt-inst2.0
      - libapt-pkg5.0
    after: [python2]
  python-apt:
    source: lp:python-apt
    source-commit: "981"
    plugin: python
    python-version: python2
    build-packages:
      - libapt-pkg-dev
    stage-packages:
      - libapt-inst2.0
      - libapt-pkg5.0
    stage:
      - -lib/python2.7/site-packages/pip-9.0.1.dist-info/RECORD
      - -lib/python2.7/site-packages/setuptools-34.1.0.dist-info/RECORD
      - -lib/python2.7/site-packages/wheel-0.29.0.dist-info/RECORD
    after: [python2]
  git:
    source: https://github.com/git/git
    source-type: git
    source-depth: 1
    plugin: autotools
    configflags:
      - --with-curl
      - --with-expat
    build-packages:
      - gettext
      - libssl-dev
      - libcurl4-openssl-dev
      - libexpat1-dev
    stage-packages:
      - libcurl3
  charm-version:
    source: workarounds
    plugin: dump
    stage:
      - charmstore-client-version
